### ISSUE TITLE
problems about environment

### ISSUE THREAD

**Issue by shether-a** [jerbarnes/direct_parsing_to_sent_graph#9]
Sorry to interrupt you, I wanna ask if I can run the code without configuring the cluster management system.

**Comment by jerbarnes** [comment]
Hi! Yes, you can run `python3 train.py` by itself, as the `run.sh` script just configures the environment for training on the cluster. You will need to have the proper python libraries installed however. @davda54, would it be possible to add a requirements.txt to the repo?

**Comment by shether-a** [comment]
ok, I get it. Thank you so much
